name: Dependency Security Scan

on:
  schedule:
    - cron: "0 0 * * 1"  # Runs weekly on Mondays
  push:
    branches:
      - main

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install safety

      - name: Run Safety Check
        run: safety check --full-report
