name: Run Pytest on Push

on: 
  push:
    branches: [ main ]  # Run tests on push to main branch
  pull_request:
    branches: [ main ]  # Run tests on PR to main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use a Linux runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # Pulls the latest code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"  # Match your local Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install all dependencies

    - name: Run Pytest
      run: pytest -v  # Run all tests with verbose output
